# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

name: $(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# Create a production build artifact from the HEAD of the master branch.
trigger: none
pr: none

pool:
  name: Azure Pipelines
  vmImage: windows-latest
  demands:
    - msbuild
    - vstest

variables:
  - template: ./common-variables.yml

stages:
  - stage: build
    jobs:
      - job: build
        steps:
          - template: ./common-templates/install-tools.yml

          - template: ./common-templates/security-pre-checks.yml

          - template: ./common-templates/common-steps.yml
            parameters:
              Official: false

          - template: ./common-templates/security-post-checks.yml
